apiVersion: 1

contactPoints:
  - orgId: 1
    name: container-email-alert

    receivers:
      - uid: container-email1
        type: email

        settings:
          addresses: samarthf@valueaddsofttech.com

          subject: >-
            {{ if eq .Status "resolved" }}
            ✅ Container Start Alert - {{ .CommonLabels.container }}
            {{ else }}
            🚨 Container Down Alert - {{ .CommonLabels.container }}
            {{ end }}

  - orgId: 1
    name: infra-email-alert

    receivers:
      - uid: infra-email1
        type: email

        settings:
          addresses: samarthf@valueaddsofttech.com

          subject: >-
            🚨 [{{ .Status | toUpper }}]
            {{ .CommonLabels.alertname }}