apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-alert

    receivers:
      - uid: email1
        type: email

        settings:
          addresses: samarthf@valueaddsofttech.com

          subject: |
            {{ .CommonLabels.alertname }}

          message: |
            {{ template "simple.message" . }}