apiVersion: 1

contactPoints:

  # =========================================
  # CONTAINER ALERTS — EMAIL
  # =========================================
  - orgId: 1
    name: container-email-alert
    receivers:
      - uid: container-email1
        type: email
        disableResolveMessage: false
        settings:
          addresses: samarthf@valueaddsofttech.com
          subject: '{{ template "container_alert_subject" . }}'
          singleEmail: true

  # =========================================
  # CONTAINER START ALERTS — EMAIL
  # =========================================
  - orgId: 1
    name: container-start-email-alert
    receivers:
      - uid: container-start-email1
        type: email
        disableResolveMessage: true
        settings:
          addresses: samarthf@valueaddsofttech.com
          subject: '{{ template "container_start_subject" . }}'
          singleEmail: true

  # =========================================
  # MONITORING ALERTS — EMAIL
  # =========================================
  - orgId: 1
    name: monitoring-email-alert
    receivers:
      - uid: monitoring-email1
        type: email
        disableResolveMessage: false
        settings:
          addresses: samarthf@valueaddsofttech.com
          subject: '{{ template "monitoring_alert_subject" . }}'
          singleEmail: true

  # =========================================
  # INFRASTRUCTURE ALERTS — EMAIL
  # =========================================
  - orgId: 1
    name: infra-email-alert
    receivers:
      - uid: infra-email1
        type: email
        disableResolveMessage: false
        settings:
          addresses: samarthf@valueaddsofttech.com
          subject: '{{ template "infra_alert_subject" . }}'
          singleEmail: true
