apiVersion: 1

policies:
  - orgId: 1
    receiver: infra-email-alert
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5m

    routes:
      - receiver: container-email-alert
        group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 5m
        matchers:
          - category="container"


      - receiver: container-start-email-alert
        group_by:
          - alertname
          - container
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 24h
        matchers:
          - category="container-start"

      - receiver: monitoring-email-alert
        group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 5m
        matchers:
          - category="monitoring"
